=== aws-deadline/deadline-cloud/src/deadline/job_attachments/asset_manifests/schemas/2023-03-03.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "AWS Deadline Cloud Asset Manifest Schema",
    "type": "object",
    "required": [
        "hashAlg",
        "paths",
        "manifestVersion",
        "totalSize"
    ],
    "properties": {
        "manifestVersion": {
            "const" : "2023-03-03",
            "description": "The version of this asset manifest."
        },
        "hashAlg": {
            "enum": ["xxh128"],
            "description": "The algorithm that the files in this manifest were hashed with"
        },
        "totalSize": {
            "type": "integer",
            "description": "The sum of all file's sizes in bytes."
        },
        "paths": {
            "type": "array",
            "description": "All files in the data set and their hashes",
            "minItems": 1,
            "items": {
                "type": "object",
                "required": [
                    "path",
                    "hash",
                    "size",
                    "mtime"
                ],
                "properties": {
                    "path": {
                        "type": "string",
                        "description": "The path to this file relative to a root directory"
                    },
                    "hash": {
                        "type": "string",
                        "description": "The hash of this file."
                    },
                    "size": {
                        "type": "integer",
                        "description": "Total size, in bytes."
                    },
                    "mtime": {
                        "type": "integer",
                        "description": "Epoch time in microseconds when the file was last modified."
                    }
                }
            }
        }
    }
}

=== aws-deadline/deadline-cloud/test/unit/deadline_job_attachments/data/manifest_v2023_03_03.json
{"hashAlg":"xxh128","manifestVersion":"2023-03-03","paths":[{"hash":"CarriageReturn","mtime":1679079744833848,"path":"\r","size":1},{"hash":"One","mtime":1679079344833868,"path":"1","size":1},{"hash":"c","mtime":1675079344833848,"path":"another_test_file","size":1},{"hash":"b","mtime":1479079344833848,"path":"test_dir/test_file","size":1},{"hash":"a","mtime":167907934333848,"path":"test_file","size":1},{"hash":"Control","mtime":1679079344833348,"path":"\u0080","size":1},{"hash":"LatinSmallLetterOWithDiaeresis","mtime":1679079344833848,"path":"\u00f6","size":1},{"hash":"EuroSign","mtime":1679079344836848,"path":"\u20ac","size":1},{"hash":"EmojiGrinningFace","mtime":1679579344833848,"path":"\ud83d\ude00","size":1},{"hash":"HebrewLetterDaletWithDagesh","mtime":1679039344833848,"path":"\ufb33","size":1}],"totalSize":10}
